Checked out a new branch robin in the base fork
darwinia-network/darwinia-docs-deprecated pull request #177
Opened 2021-07-13 21:42 UTC by robinwei-itering

1. Added Section of Cross-chain Transfer;
2. Added Section of Staking;
3. Minor fixes to Section of Accounts;
4. Entries need to be inserted into some config files to make new contents visible.

2021-07-14 05:13 UTC, HackFisher requested changes

2021-07-14 05:13 UTC, HackFisher commented on content/zh-CN/quick-start-staking-nominator.md
> +- 拥有至少一个合法账户；
```suggestion
- 拥有至少一个有效账户；
```

2021-07-14 05:13 UTC, HackFisher commented on content/zh-CN/quick-start-crosschain-transfer-ex-withdraw.md
> +![Crosschain](assets/quick_start_zh-CN/darwinia-crosschain-transfer-huobi_zh-CN.png)
这个教程建议去掉，不同的交易所可能有不同的方式，不建议在文档内包括CEX相关的教程。如有必要，可以提供交易所的公告或者教程文档链接即可

2021-07-14 05:21 UTC, 1022ranji commented on content/zh-CN/quick-start-crosschain-transfer-ex-withdraw.md
> +![Crosschain](assets/quick_start_zh-CN/darwinia-crosschain-transfer-huobi_zh-CN.png)
交易所提币到主网的教程是社区中呼声很高的一个需求，不同交易所的不一样，所以只需提示其在提币时选择ERC20的方式即可，其余可用交易所提币教程的文档链接。

2021-08-02 08:19 UTC, wuminzhe approved these changes

2021-08-02 08:19 UTC, merged